<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [rabbitmq-discuss] Weird unicode error popping up in pika 0.9.6
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20Weird%20unicode%20error%20popping%20up%20in%20pika%200.9.6&In-Reply-To=%3Cc5e9ccf1-fdcc-4106-837f-09045044a757%40googlegroups.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="021833.html">
   <LINK REL="Next"  HREF="021836.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[rabbitmq-discuss] Weird unicode error popping up in pika 0.9.6</H1>
    <B>Stephen Young</B> 
    <A HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20Weird%20unicode%20error%20popping%20up%20in%20pika%200.9.6&In-Reply-To=%3Cc5e9ccf1-fdcc-4106-837f-09045044a757%40googlegroups.com%3E"
       TITLE="[rabbitmq-discuss] Weird unicode error popping up in pika 0.9.6">stephen.t.young at gmail.com
       </A><BR>
    <I>Mon Aug 13 16:22:17 BST 2012</I>
    <P><UL>
        <LI>Previous message: <A HREF="021833.html">[rabbitmq-discuss] Weird unicode error popping up in pika 0.9.6
</A></li>
        <LI>Next message: <A HREF="021836.html">[rabbitmq-discuss] highly available shovel in a cluster
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#21834">[ date ]</a>
              <a href="thread.html#21834">[ thread ]</a>
              <a href="subject.html#21834">[ subject ]</a>
              <a href="author.html#21834">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Update: was because my queue name and routing key were unicode strings - 
pulled the latest commit to pika which now checks for that, helped me 
debug. Looks like everything has to be a bytestring in order for the 
_marshal function to generate a valid payload, otherwise python tries to 
encode everything into unicode

On Monday, August 13, 2012 9:40:53 AM UTC-4, Stephen Young wrote:
&gt;<i>
</I>&gt;<i> Hi there,
</I>&gt;<i>
</I>&gt;<i> I've been using version 0.9,6 pika in a stable environment for about a 
</I>&gt;<i> month and am suddenly encountering a unicode error that looks like:
</I>&gt;<i>
</I>&gt;<i> Traceback (most recent call last):
</I>&gt;<i>   File 
</I>&gt;<i> &quot;/devel/lib/python2.7/site-packages/Twisted-12.0.0-py2.7-macosx-10.7-x86_64.egg/twisted/internet/selectreactor.py&quot;, 
</I>&gt;<i> line 150, in _doReadOrWrite
</I>&gt;<i>     why = getattr(selectable, method)()
</I>&gt;<i>   File 
</I>&gt;<i> &quot;/devel/lib/python2.7/site-packages/Twisted-12.0.0-py2.7-macosx-10.7-x86_64.egg/twisted/internet/tcp.py&quot;, 
</I>&gt;<i> line 199, in doRead
</I>&gt;<i>     rval = self.protocol.dataReceived(data)
</I>&gt;<i>   File &quot;/devel/src/pika/pika/adapters/twisted_connection.py&quot;, line 378, in 
</I>&gt;<i> dataReceived
</I>&gt;<i>     self._on_data_available(data)
</I>&gt;<i>   File &quot;/devel/src/pika/pika/connection.py&quot;, line 701, in 
</I>&gt;<i> _on_data_available
</I>&gt;<i>     frame)                 # Args
</I>&gt;<i>   File &quot;/devel/src/pika/pika/callback.py&quot;, line 161, in process
</I>&gt;<i>     callback(*args, **keywords)
</I>&gt;<i>   File &quot;/devel/src/pika/pika/channel.py&quot;, line 152, in 
</I>&gt;<i> _on_synchronous_complete
</I>&gt;<i>     self.rpc(*method)
</I>&gt;<i>   File &quot;/devel/src/pika/pika/channel.py&quot;, line 114, in rpc
</I>&gt;<i>     self.send_method(method)
</I>&gt;<i>   File &quot;/devel/src/pika/pika/channel.py&quot;, line 121, in send_method
</I>&gt;<i>     self.connection._send_method(self.channel_number, method, content)
</I>&gt;<i>   File &quot;/devel/src/pika/pika/connection.py&quot;, line 781, in _send_method
</I>&gt;<i>     self._send_frame(pika.frame.Method(channel_number, method))
</I>&gt;<i>   File &quot;/devel/src/pika/pika/adapters/twisted_connection.py&quot;, line 355, in 
</I>&gt;<i> _send_frame
</I>&gt;<i>     marshalled_frame = frame.marshal()
</I>&gt;<i>   File &quot;/devel/src/pika/pika/frame.py&quot;, line 65, in marshal
</I>&gt;<i>     return self._marshal(pieces)
</I>&gt;<i>   File &quot;/devel/src/pika/pika/frame.py&quot;, line 40, in _marshal
</I>&gt;<i>     len(payload)) + payload + chr(spec.FRAME_END)
</I>&gt;<i> exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in 
</I>&gt;<i> position 0: ordinal not in range(128)
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> I'm using the twisted adapter, and I have a hunch that the problem is 
</I>&gt;<i> coming from there somewhere, but I'm pretty lost as far as what to do to 
</I>&gt;<i> fix this bug. Anyone have any ideas?
</I>&gt;<i>
</I>&gt;<i> Cheers,
</I>&gt;<i> Stephen 
</I>&gt;<i>
</I>-------------- next part --------------
An HTML attachment was scrubbed...
URL: &lt;<A HREF="http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/attachments/20120813/b5fbba8b/attachment.htm">http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/attachments/20120813/b5fbba8b/attachment.htm</A>&gt;
</PRE>












<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="021833.html">[rabbitmq-discuss] Weird unicode error popping up in pika 0.9.6
</A></li>
	<LI>Next message: <A HREF="021836.html">[rabbitmq-discuss] highly available shovel in a cluster
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#21834">[ date ]</a>
              <a href="thread.html#21834">[ thread ]</a>
              <a href="subject.html#21834">[ subject ]</a>
              <a href="author.html#21834">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">More information about the rabbitmq-discuss
mailing list</a><br>
</body></html>
