<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [rabbitmq-discuss] Socket Error 104 when connecting to rabbit	cluster
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20Socket%20Error%20104%20when%20connecting%20to%20rabbit%0A%09cluster&In-Reply-To=%3CCALPqkipyVrHoBC0fv3fKonCzCPgNAtbRLu4bpMkLABt97tEpqw%40mail.gmail.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="028533.html">
   <LINK REL="Next"  HREF="028539.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[rabbitmq-discuss] Socket Error 104 when connecting to rabbit	cluster</H1>
    <B>Brett Cameron</B> 
    <A HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20Socket%20Error%20104%20when%20connecting%20to%20rabbit%0A%09cluster&In-Reply-To=%3CCALPqkipyVrHoBC0fv3fKonCzCPgNAtbRLu4bpMkLABt97tEpqw%40mail.gmail.com%3E"
       TITLE="[rabbitmq-discuss] Socket Error 104 when connecting to rabbit	cluster">brett.r.cameron at gmail.com
       </A><BR>
    <I>Fri Jul 12 10:22:21 BST 2013</I>
    <P><UL>
        <LI>Previous message: <A HREF="028533.html">[rabbitmq-discuss] Socket Error 104 when connecting to rabbit	cluster
</A></li>
        <LI>Next message: <A HREF="028539.html">[rabbitmq-discuss] Socket Error 104 when connecting to rabbit	cluster
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#28535">[ date ]</a>
              <a href="thread.html#28535">[ thread ]</a>
              <a href="subject.html#28535">[ subject ]</a>
              <a href="author.html#28535">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Robert,

Curious. The connection_closed_abruptly log messages typically indicate
that the client has done something strange; they are just (relatively
innocuous) warnings from RabbitMQ's perspective. Can you connect from
another server?

Brett


On Fri, Jul 12, 2013 at 9:07 PM, Rubo Liang &lt;<A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">liangrubo at bytedance.com</A>&gt; wrote:

&gt;<i> Hi Brett,
</I>&gt;<i>
</I>&gt;<i> message from rabbit log file:
</I>&gt;<i> =INFO REPORT==== 12-Jul-2013::17:00:34 ===
</I>&gt;<i> accepting AMQP connection &lt;0.4818.7&gt; (10.4.16.221:61833 -&gt;
</I>&gt;<i> 10.4.16.221:5672)
</I>&gt;<i>
</I>&gt;<i> =WARNING REPORT==== 12-Jul-2013::17:00:34 ===
</I>&gt;<i> closing AMQP connection &lt;0.4818.7&gt; (10.4.16.221:61833 -&gt; 10.4.16.221:5672
</I>&gt;<i> ):
</I>&gt;<i> connection_closed_abruptly
</I>&gt;<i>
</I>&gt;<i> It seems to be a socket problem, but I can immediately connect to the
</I>&gt;<i> server with telnet.
</I>&gt;<i>
</I>&gt;<i> Thanks.
</I>&gt;<i>
</I>&gt;<i> On Fri, Jul 12, 2013 at 4:16 PM, Brett Cameron &lt;<A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">brett.r.cameron at gmail.com</A>&gt;wrote:
</I>&gt;<i>
</I>&gt;&gt;<i> Robert,
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> For what it is worth &quot;Socket Error on fd 3: 104&quot; equates to &quot;Connection
</I>&gt;&gt;<i> reset by peer&quot;. Chances are there will be something in RabbitMQ's log files
</I>&gt;&gt;<i> that will provide more information about what is going on - could be a
</I>&gt;&gt;<i> timeout or something like that.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Brett
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> On Fri, Jul 12, 2013 at 7:19 PM, Rubo Liang &lt;<A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">liangrubo at bytedance.com</A>&gt;wrote:
</I>&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> Hi,
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> I have a rabbit cluster with 3 servers. I got error message like
</I>&gt;&gt;&gt;<i> following when trying to connect to it (the cluster has worked well for 2
</I>&gt;&gt;&gt;<i> days):
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> Socket Error on fd 3: 104
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> Details:
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> The cluster has 3 servers: A, B, C. Clients connect to server A. I run 'rabbitmqctl
</I>&gt;&gt;&gt;<i> stop_app; rabbitmqctl reset; rabbitmqctl start_app' on Server A to bring
</I>&gt;&gt;&gt;<i> the service back. Then I try to connect to server B but get the same error.
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> I can telnet rabbit port on server B.
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> ~$ rabbitmqctl list_queues
</I>&gt;&gt;&gt;<i> Listing queues ...
</I>&gt;&gt;&gt;<i> ha.snssdk.log   0
</I>&gt;&gt;&gt;<i> ha.snssdk.log.dispatch  0
</I>&gt;&gt;&gt;<i> ha.snssdk.log.output    0
</I>&gt;&gt;&gt;<i> ...done.
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> 'rabbitmqctl report' output:
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> <A HREF="https://gist.github.com/liangrubo/5982515">https://gist.github.com/liangrubo/5982515</A>
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> pika stacktrace:
</I>&gt;&gt;&gt;<i>   File
</I>&gt;&gt;&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py&quot;,
</I>&gt;&gt;&gt;<i> line 61, in __init__
</I>&gt;&gt;&gt;<i>     super(BaseConnection, self).__init__(parameters, on_open_callback)
</I>&gt;&gt;&gt;<i>   File &quot;/usr/local/lib/python2.7/dist-packages/pika/connection.py&quot;, line
</I>&gt;&gt;&gt;<i> 513, in __init__
</I>&gt;&gt;&gt;<i>     self._connect()
</I>&gt;&gt;&gt;<i>   File &quot;/usr/local/lib/python2.7/dist-packages/pika/connection.py&quot;, line
</I>&gt;&gt;&gt;<i> 804, in _connect
</I>&gt;&gt;&gt;<i>     self._adapter_connect()
</I>&gt;&gt;&gt;<i>   File
</I>&gt;&gt;&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py&quot;,
</I>&gt;&gt;&gt;<i> line 146, in _adapter_connect
</I>&gt;&gt;&gt;<i>     self.process_data_events()
</I>&gt;&gt;&gt;<i>   File
</I>&gt;&gt;&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py&quot;,
</I>&gt;&gt;&gt;<i> line 88, in process_data_events
</I>&gt;&gt;&gt;<i>     if self._handle_read():
</I>&gt;&gt;&gt;<i>   File
</I>&gt;&gt;&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py&quot;,
</I>&gt;&gt;&gt;<i> line 184, in _handle_read
</I>&gt;&gt;&gt;<i>     super(BlockingConnection, self)._handle_read()
</I>&gt;&gt;&gt;<i>   File
</I>&gt;&gt;&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py&quot;,
</I>&gt;&gt;&gt;<i> line 300, in _handle_read
</I>&gt;&gt;&gt;<i>     return self._handle_error(error)
</I>&gt;&gt;&gt;<i>   File
</I>&gt;&gt;&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py&quot;,
</I>&gt;&gt;&gt;<i> line 264, in _handle_error
</I>&gt;&gt;&gt;<i>     self._handle_disconnect()
</I>&gt;&gt;&gt;<i>   File
</I>&gt;&gt;&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py&quot;,
</I>&gt;&gt;&gt;<i> line 181, in _handle_disconnect
</I>&gt;&gt;&gt;<i>     self._on_connection_closed(None, True)
</I>&gt;&gt;&gt;<i>   File
</I>&gt;&gt;&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py&quot;,
</I>&gt;&gt;&gt;<i> line 235, in _on_connection_closed
</I>&gt;&gt;&gt;<i>     raise exceptions.AMQPConnectionError(*self.closing)
</I>&gt;&gt;&gt;<i> pika.exceptions.AMQPConnectionError: (0, '')
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> Any help is appreciated.
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> Thanks.
</I>&gt;&gt;&gt;<i> Robert
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> _______________________________________________
</I>&gt;&gt;&gt;<i> rabbitmq-discuss mailing list
</I>&gt;&gt;&gt;<i> <A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">rabbitmq-discuss at lists.rabbitmq.com</A>
</I>&gt;&gt;&gt;<i> <A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss</A>
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> _______________________________________________
</I>&gt;&gt;<i> rabbitmq-discuss mailing list
</I>&gt;&gt;<i> <A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">rabbitmq-discuss at lists.rabbitmq.com</A>
</I>&gt;&gt;<i> <A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss</A>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> _______________________________________________
</I>&gt;<i> rabbitmq-discuss mailing list
</I>&gt;<i> <A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">rabbitmq-discuss at lists.rabbitmq.com</A>
</I>&gt;<i> <A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss</A>
</I>&gt;<i>
</I>&gt;<i>
</I>-------------- next part --------------
An HTML attachment was scrubbed...
URL: &lt;<A HREF="http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/attachments/20130712/27f22811/attachment.htm">http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/attachments/20130712/27f22811/attachment.htm</A>&gt;
</PRE>



























































<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="028533.html">[rabbitmq-discuss] Socket Error 104 when connecting to rabbit	cluster
</A></li>
	<LI>Next message: <A HREF="028539.html">[rabbitmq-discuss] Socket Error 104 when connecting to rabbit	cluster
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#28535">[ date ]</a>
              <a href="thread.html#28535">[ thread ]</a>
              <a href="subject.html#28535">[ subject ]</a>
              <a href="author.html#28535">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">More information about the rabbitmq-discuss
mailing list</a><br>
</body></html>
