<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [rabbitmq-discuss] Pika: Error when doing a stop_consuming() from a timeout callback
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20Pika%3A%20Error%20when%20doing%20a%20stop_consuming%28%29%0A%20from%20a%20timeout%20callback&In-Reply-To=%3C4E31EC52.6000705%40gmail.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="014231.html">
   <LINK REL="Next"  HREF="014236.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[rabbitmq-discuss] Pika: Error when doing a stop_consuming() from a timeout callback</H1>
    <B>Christian Haintz</B> 
    <A HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20Pika%3A%20Error%20when%20doing%20a%20stop_consuming%28%29%0A%20from%20a%20timeout%20callback&In-Reply-To=%3C4E31EC52.6000705%40gmail.com%3E"
       TITLE="[rabbitmq-discuss] Pika: Error when doing a stop_consuming() from a timeout callback">christian.haintz at gmail.com
       </A><BR>
    <I>Fri Jul 29 00:10:10 BST 2011</I>
    <P><UL>
        <LI>Previous message: <A HREF="014231.html">[rabbitmq-discuss] Pika: Error when doing a stop_consuming() from a timeout callback
</A></li>
        <LI>Next message: <A HREF="014236.html">[rabbitmq-discuss] RabbitMQ + CEP
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#14232">[ date ]</a>
              <a href="thread.html#14232">[ thread ]</a>
              <a href="subject.html#14232">[ subject ]</a>
              <a href="author.html#14232">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>On 29/7/11 1:05, Gavin M. Roy wrote:
&gt;<i> I'll take a look shortly, mind opening a issue on github for me to track
</I>&gt;<i> with?
</I>
Opened an issue on github (<A HREF="https://github.com/pika/pika/issues/75">https://github.com/pika/pika/issues/75</A>)

Thank you for your help!

Best Regards,
Christian


&gt;<i>
</I>&gt;<i> On Thursday, July 28, 2011 at 7:04 PM, Christian Haintz wrote:
</I>&gt;<i>
</I>&gt;&gt;<i> On 29/7/11 24:54, Gavin M. Roy wrote:
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> On Thursday, July 28, 2011 at 6:45 PM, Christian Haintz wrote:
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> Hi,
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> I want to stop the consuming loop of a BlockingConnection after some
</I>&gt;&gt;&gt;&gt;<i> timeout. I used the following code. Producer is not running because I
</I>&gt;&gt;&gt;&gt;<i> want to simulate the timeout. Current pika version is used from github.
</I>&gt;&gt;&gt;<i> I'd not consider the master branch on Pika stable, which is one of the
</I>&gt;&gt;&gt;<i> reasons I've not tagged 0.9.6. I'd do a pip install of 0.9.5 and see if
</I>&gt;&gt;&gt;<i> that solves your problem.
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> Gavin
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> I tried it first with 0.9.5 but that leads to a different error which
</I>&gt;&gt;<i> seams to be fixed in the master branch (used the same test code as in
</I>&gt;&gt;<i> the previous e-mail):
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> --------8&lt;--------- snip ----------8&lt;-----------
</I>&gt;&gt;<i> python pika_test.py
</I>&gt;&gt;<i> Traceback (most recent call last):
</I>&gt;&gt;<i> File &quot;pika_test.py&quot;, line 21, in &lt;module&gt;
</I>&gt;&gt;<i> channel.start_consuming()
</I>&gt;&gt;<i> File
</I>&gt;&gt;<i> &quot;build/bdist.macosx-10.6-universal/egg/pika/adapters/blocking_connection.py&quot;,
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> line 293, in start_consuming
</I>&gt;&gt;<i> File
</I>&gt;&gt;<i> &quot;build/bdist.macosx-10.6-universal/egg/pika/adapters/blocking_connection.py&quot;,
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> line 103, in process_data_events
</I>&gt;&gt;<i> File
</I>&gt;&gt;<i> &quot;build/bdist.macosx-10.6-universal/egg/pika/adapters/blocking_connection.py&quot;,
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> line 157, in process_timeouts
</I>&gt;&gt;<i> NameError: global name 'log' is not defined
</I>&gt;&gt;<i> --------8&lt;------- snip end --------8&lt;-----------
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Best Regards,
</I>&gt;&gt;<i> Christian
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>     --------8&lt;--------- snip ----------8&lt;-----------
</I>&gt;&gt;&gt;<i>     import pika
</I>&gt;&gt;&gt;<i>     connection = pika.BlockingConnection(pika.ConnectionParameters(
</I>&gt;&gt;&gt;<i>     host='localhost'))
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>     channel = connection.channel()
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>     result = channel.queue_declare(exclusive=True)
</I>&gt;&gt;&gt;<i>     callback_queue = result.method.queue
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>     def on_response(self, ch, method, props, body):
</I>&gt;&gt;&gt;<i>     #do some processing
</I>&gt;&gt;&gt;<i>     channel.stop_consuming()
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>     # normaly i do some publish here but that's not relevant
</I>&gt;&gt;&gt;<i>     # to reproduce the error
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>     channel.basic_consume(on_response, no_ack=True,
</I>&gt;&gt;&gt;<i>     queue=callback_queue)
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>     def panic():
</I>&gt;&gt;&gt;<i>     channel.stop_consuming()
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>     connection.add_timeout(1, panic)
</I>&gt;&gt;&gt;<i>     channel.start_consuming()
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>     --------8&lt;------- snip end --------8&lt;-----------
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>     But I get the following error:
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>     --------8&lt;--------- snip ----------8&lt;-----------
</I>&gt;&gt;&gt;<i>     $ python pika_test.py
</I>&gt;&gt;&gt;<i>     /Users/christian/devel/pika/pika/callback.py:69: UserWarning:
</I>&gt;&gt;&gt;<i>     CallbackManager.add: Duplicate callback found for &quot;1:Basic.CancelOk&quot;
</I>&gt;&gt;&gt;<i>     (self.__class__.__name__, prefix, key))
</I>&gt;&gt;&gt;<i>     Traceback (most recent call last):
</I>&gt;&gt;&gt;<i>     File &quot;pika_test.py&quot;, line 21, in &lt;module&gt;
</I>&gt;&gt;&gt;<i>     channel.start_consuming()
</I>&gt;&gt;&gt;<i>     File
</I>&gt;&gt;&gt;<i>     &quot;/Users/christian/devel/pika/pika/adapters/blocking_connection.py&quot;,
</I>&gt;&gt;&gt;<i>     line
</I>&gt;&gt;&gt;<i>     307, in start_consuming
</I>&gt;&gt;&gt;<i>     self.transport.connection.process_data_events()
</I>&gt;&gt;&gt;<i>     File
</I>&gt;&gt;&gt;<i>     &quot;/Users/christian/devel/pika/pika/adapters/blocking_connection.py&quot;,
</I>&gt;&gt;&gt;<i>     line
</I>&gt;&gt;&gt;<i>     104, in process_data_events
</I>&gt;&gt;&gt;<i>     self.process_timeouts()
</I>&gt;&gt;&gt;<i>     File
</I>&gt;&gt;&gt;<i>     &quot;/Users/christian/devel/pika/pika/adapters/blocking_connection.py&quot;,
</I>&gt;&gt;&gt;<i>     line
</I>&gt;&gt;&gt;<i>     164, in process_timeouts
</I>&gt;&gt;&gt;<i>     self._timeouts[timeout_id]['handler']()
</I>&gt;&gt;&gt;<i>     File &quot;pika_test.py&quot;, line 18, in panic
</I>&gt;&gt;&gt;<i>     channel.stop_consuming()
</I>&gt;&gt;&gt;<i>     File
</I>&gt;&gt;&gt;<i>     &quot;/Users/christian/devel/pika/pika/adapters/blocking_connection.py&quot;,
</I>&gt;&gt;&gt;<i>     line
</I>&gt;&gt;&gt;<i>     318, in stop_consuming
</I>&gt;&gt;&gt;<i>     self.basic_cancel(consumer_tag)
</I>&gt;&gt;&gt;<i>     File &quot;/Users/christian/devel/pika/pika/channel.py&quot;, line 333, in
</I>&gt;&gt;&gt;<i>     basic_cancel
</I>&gt;&gt;&gt;<i>     self._on_cancel_ok, [spec.Basic.CancelOk])
</I>&gt;&gt;&gt;<i>     File
</I>&gt;&gt;&gt;<i>     &quot;/Users/christian/devel/pika/pika/adapters/blocking_connection.py&quot;,
</I>&gt;&gt;&gt;<i>     line
</I>&gt;&gt;&gt;<i>     220, in rpc
</I>&gt;&gt;&gt;<i>     self.send_method(method, None, wait)
</I>&gt;&gt;&gt;<i>     File
</I>&gt;&gt;&gt;<i>     &quot;/Users/christian/devel/pika/pika/adapters/blocking_connection.py&quot;,
</I>&gt;&gt;&gt;<i>     line
</I>&gt;&gt;&gt;<i>     249, in send_method
</I>&gt;&gt;&gt;<i>     self.connection.process_data_events()
</I>&gt;&gt;&gt;<i>     File
</I>&gt;&gt;&gt;<i>     &quot;/Users/christian/devel/pika/pika/adapters/blocking_connection.py&quot;,
</I>&gt;&gt;&gt;<i>     line
</I>&gt;&gt;&gt;<i>     104, in process_data_events
</I>&gt;&gt;&gt;<i>     self.process_timeouts()
</I>&gt;&gt;&gt;<i>     File
</I>&gt;&gt;&gt;<i>     &quot;/Users/christian/devel/pika/pika/adapters/blocking_connection.py&quot;,
</I>&gt;&gt;&gt;<i>     line
</I>&gt;&gt;&gt;<i>     164, in process_timeouts
</I>&gt;&gt;&gt;<i>     self._timeouts[timeout_id]['handler']()
</I>&gt;&gt;&gt;<i>     File &quot;pika_test.py&quot;, line 18, in panic
</I>&gt;&gt;&gt;<i>     channel.stop_consuming()
</I>&gt;&gt;&gt;<i>     File
</I>&gt;&gt;&gt;<i>     &quot;/Users/christian/devel/pika/pika/adapters/blocking_connection.py&quot;,
</I>&gt;&gt;&gt;<i>     line
</I>&gt;&gt;&gt;<i>     318, in stop_consuming
</I>&gt;&gt;&gt;<i>     self.basic_cancel(consumer_tag)
</I>&gt;&gt;&gt;<i>     File &quot;/Users/christian/devel/pika/pika/channel.py&quot;, line 333, in
</I>&gt;&gt;&gt;<i>     basic_cancel
</I>&gt;&gt;&gt;<i>     self._on_cancel_ok, [spec.Basic.CancelOk])
</I>&gt;&gt;&gt;<i>     File
</I>&gt;&gt;&gt;<i>     &quot;/Users/christian/devel/pika/pika/adapters/blocking_connection.py&quot;,
</I>&gt;&gt;&gt;<i>     line
</I>&gt;&gt;&gt;<i>     209, in rpc
</I>&gt;&gt;&gt;<i>     self._on_rpc_complete)
</I>&gt;&gt;&gt;<i>     TypeError: 'NoneType' object is not iterable
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>     What I am doing wrong? Are the timeout callbacks not capable of
</I>&gt;&gt;&gt;<i>     stopping
</I>&gt;&gt;&gt;<i>     the consumer?
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>     Regards,
</I>&gt;&gt;&gt;<i>     Christian
</I>&gt;&gt;&gt;<i>     _______________________________________________
</I>&gt;&gt;&gt;<i>     rabbitmq-discuss mailing list
</I>&gt;&gt;&gt;<i>     <A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">rabbitmq-discuss at lists.rabbitmq.com</A>
</I>&gt;&gt;&gt;<i>     &lt;mailto:<A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">rabbitmq-discuss at lists.rabbitmq.com</A>&gt;
</I>&gt;&gt;&gt;<i>     &lt;mailto:<A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">rabbitmq-discuss at lists.rabbitmq.com</A>&gt;
</I>&gt;&gt;&gt;<i>     <A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss</A>
</I>&gt;&gt;<i>
</I>&gt;<i>
</I>
</PRE>










<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="014231.html">[rabbitmq-discuss] Pika: Error when doing a stop_consuming() from a timeout callback
</A></li>
	<LI>Next message: <A HREF="014236.html">[rabbitmq-discuss] RabbitMQ + CEP
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#14232">[ date ]</a>
              <a href="thread.html#14232">[ thread ]</a>
              <a href="subject.html#14232">[ subject ]</a>
              <a href="author.html#14232">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">More information about the rabbitmq-discuss
mailing list</a><br>
</body></html>
