<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [rabbitmq-discuss] Python Pika Unicode error
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20Python%20Pika%20Unicode%20error&In-Reply-To=%3C1363126619567-25416.post%40n5.nabble.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="025888.html">
   <LINK REL="Next"  HREF="025917.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[rabbitmq-discuss] Python Pika Unicode error</H1>
    <B>9ners</B> 
    <A HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20Python%20Pika%20Unicode%20error&In-Reply-To=%3C1363126619567-25416.post%40n5.nabble.com%3E"
       TITLE="[rabbitmq-discuss] Python Pika Unicode error">jay0555 at hotmail.com
       </A><BR>
    <I>Tue Mar 12 22:16:59 GMT 2013</I>
    <P><UL>
        <LI>Previous message: <A HREF="025888.html">[rabbitmq-discuss] ANN Bunny 0.9.0.pre8
</A></li>
        <LI>Next message: <A HREF="025917.html">[rabbitmq-discuss] Python Pika Unicode error
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#25889">[ date ]</a>
              <a href="thread.html#25889">[ thread ]</a>
              <a href="subject.html#25889">[ subject ]</a>
              <a href="author.html#25889">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>getting the following while trying to receive raw data (from UDP source
routed to rabbitmq exchange). Text or Syslog format works alright but errors
out with raw message types. Please help

Exit press CTRL+C
Traceback (most recent call last):
  File &quot;receive_logs.py&quot;, line 27, in &lt;module&gt;
    channel.start_consuming()
  File
&quot;/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py&quot;,
line 771, in start_consuming
    self.connection.process_data_events()
  File
&quot;/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py&quot;,
line 129, in process_data_events
    if self._handle_read():
  File
&quot;/usr/lib/python2.6/site-packages/pika/adapters/blocking_connection.py&quot;,
line 232, in _handle_read
    super(BlockingConnection, self)._handle_read()
  File &quot;/usr/lib/python2.6/site-packages/pika/adapters/base_connection.py&quot;,
line 307, in _handle_read
    self._on_data_available(data)
  File &quot;/usr/lib/python2.6/site-packages/pika/connection.py&quot;, line 1141, in
_on_data_available
    consumed_count, frame_value = self._read_frame()
  File &quot;/usr/lib/python2.6/site-packages/pika/connection.py&quot;, line 1208, in
_read_frame
    return frame.decode_frame(self._frame_buffer)
  File &quot;/usr/lib/python2.6/site-packages/pika/frame.py&quot;, line 240, in
decode_frame
    method.decode(frame_data, 4)
  File &quot;/usr/lib/python2.6/site-packages/pika/spec.py&quot;, line 1902, in decode
    self.routing_key = encoded[offset:offset + length].decode('utf8')
  File &quot;/usr/lib64/python2.6/encodings/utf_8.py&quot;, line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 26-27:
invalid continuation byte


Code :
#!/usr/bin/env python
import pika
import sys

connection = pika.BlockingConnection(pika.ConnectionParameters(
        host='localhost'))
channel = connection.channel()

#channel.exchange_declare(exchange='topic_logs',type='topic')

result = channel.queue_declare(exclusive=False)
queue_name = result.method.queue

channel.queue_bind(exchange='collector.raw',
                       queue=queue_name,
                       routing_key=&quot;#&quot;)

print ' [*] Waiting for logs. To exit press CTRL+C'

def callback(ch, method, properties, body):
    print &quot; [x] %r:%r&quot; % (method.routing_key, body,)

channel.basic_consume(callback,
                      queue=queue_name,
                      no_ack=True)

channel.start_consuming()






--
View this message in context: <A HREF="http://rabbitmq.1065348.n5.nabble.com/Python-Pika-Unicode-error-tp25416.html">http://rabbitmq.1065348.n5.nabble.com/Python-Pika-Unicode-error-tp25416.html</A>
Sent from the RabbitMQ mailing list archive at Nabble.com.
</PRE>
























<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="025888.html">[rabbitmq-discuss] ANN Bunny 0.9.0.pre8
</A></li>
	<LI>Next message: <A HREF="025917.html">[rabbitmq-discuss] Python Pika Unicode error
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#25889">[ date ]</a>
              <a href="thread.html#25889">[ thread ]</a>
              <a href="subject.html#25889">[ subject ]</a>
              <a href="author.html#25889">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">More information about the rabbitmq-discuss
mailing list</a><br>
</body></html>
