<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [rabbitmq-discuss] Pika reconnection error
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20Pika%20reconnection%20error&In-Reply-To=%3CAANLkTimUuhxdF%2Bqn2t70SCdm21cbbqLwXOQh2vG%3DX%3D_C%40mail.gmail.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="011348.html">
   <LINK REL="Next"  HREF="011350.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[rabbitmq-discuss] Pika reconnection error</H1>
    <B>Jason J. W. Williams</B> 
    <A HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20Pika%20reconnection%20error&In-Reply-To=%3CAANLkTimUuhxdF%2Bqn2t70SCdm21cbbqLwXOQh2vG%3DX%3D_C%40mail.gmail.com%3E"
       TITLE="[rabbitmq-discuss] Pika reconnection error">jasonjwwilliams at gmail.com
       </A><BR>
    <I>Mon Feb 21 00:13:25 GMT 2011</I>
    <P><UL>
        <LI>Previous message: <A HREF="011348.html">[rabbitmq-discuss] Pika reconnection error
</A></li>
        <LI>Next message: <A HREF="011350.html">[rabbitmq-discuss] Pika reconnection error
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#11349">[ date ]</a>
              <a href="thread.html#11349">[ thread ]</a>
              <a href="subject.html#11349">[ subject ]</a>
              <a href="author.html#11349">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>BTW this problem only seems to occur when <A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">rabbit at Phantome</A> is restarted
while the consumer is connected to it. Reconnections occur properly
when restarting <A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">rabbit_1 at Phantome</A> and <A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">rabbit_2 at Phantome</A> while the
consumer is connected.

Status of node <A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">rabbit_1 at Phantome</A> ...
[{running_applications,[{rabbit,&quot;RabbitMQ&quot;,&quot;2.3.0&quot;},
                        {mnesia,&quot;MNESIA  CXC 138 12&quot;,&quot;4.4.16&quot;},
                        {os_mon,&quot;CPO  CXC 138 46&quot;,&quot;2.2.5&quot;},
                        {sasl,&quot;SASL  CXC 138 11&quot;,&quot;2.1.9.2&quot;},
                        {stdlib,&quot;ERTS  CXC 138 10&quot;,&quot;1.17.2&quot;},
                        {kernel,&quot;ERTS  CXC 138 10&quot;,&quot;2.14.2&quot;}]},
 {nodes,[{disc,[<A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">rabbit_1 at Phantome</A><A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">,rabbit at Phantome</A>]},
         {ram,[<A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">rabbit_2 at Phantome</A>]}]},
 {running_nodes,[<A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">rabbit at Phantome</A><A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">,rabbit_2 at Phantome</A><A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">,rabbit_1 at Phantome</A>]}]
...done.

-J

On Sun, Feb 20, 2011 at 5:04 PM, Jason J. W. Williams
&lt;<A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">jasonjwwilliams at gmail.com</A>&gt; wrote:
&gt;<i> Hi Guys,
</I>&gt;<i>
</I>&gt;<i> Having some issues with a test cluster setup. It's a 3-node cluster
</I>&gt;<i> with 2-disk and 1-RAM nodes. The RAM node is joined to both disk
</I>&gt;<i> nodes.
</I>&gt;<i>
</I>&gt;<i> <A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">rabbit at Phantome</A> - disk
</I>&gt;<i> <A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">rabbit_1 at Phantome</A> - disk
</I>&gt;<i> <A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">rabbit_2 at Phantome</A> - RAM
</I>&gt;<i>
</I>&gt;<i> In front of the cluster is an HAProxy instance listening on port 5670
</I>&gt;<i> doing simple round-robin TCP load balancing between the cluster
</I>&gt;<i> members.
</I>&gt;<i>
</I>&gt;<i> As long as all the nodes are running I can have my consumer connect
</I>&gt;<i> through the load balancer to any node and successfully consume.
</I>&gt;<i> Likewise with the producer. However, when I shutdown the node the
</I>&gt;<i> consumer is currently connected to and allow Pika to do the
</I>&gt;<i> reconnection, I get this error:
</I>&gt;<i>
</I>&gt;<i> error: uncaptured python exception, closing channel
</I>&gt;<i> &lt;pika.asyncore_adapter.RabbitDispatcher connected at 0x632350&gt; (&lt;class
</I>&gt;<i> 'pika.exceptions.ChannelClosed'&gt;:Connection.Close(class_id = 0,
</I>&gt;<i> method_id = 0, reply_code = 541, reply_text = 'INTERNAL_ERROR')
</I>&gt;<i> [/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/asyncore.py|read|74]
</I>&gt;<i> [/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/asyncore.py|handle_read_event|413]
</I>&gt;<i> [build/bdist.macosx-10.6-universal/egg/pika/asyncore_adapter.py|handle_read|86]
</I>&gt;<i> [build/bdist.macosx-10.6-universal/egg/pika/connection.py|on_data_available|268]
</I>&gt;<i> [build/bdist.macosx-10.6-universal/egg/pika/connection.py|_login2|375]
</I>&gt;<i> [build/bdist.macosx-10.6-universal/egg/pika/connection.py|handle_connection_open|201]
</I>&gt;<i> [cluster_test_consumer.py|on_connection_open|53]
</I>&gt;<i> [build/bdist.macosx-10.6-universal/egg/pika/spec.py|queue_declare|3003]
</I>&gt;<i> [build/bdist.macosx-10.6-universal/egg/pika/channel.py|_rpc|187]
</I>&gt;<i> [build/bdist.macosx-10.6-universal/egg/pika/connection.py|_rpc|326]
</I>&gt;<i> [build/bdist.macosx-10.6-universal/egg/pika/channel.py|wait_for_reply|125]
</I>&gt;<i> [build/bdist.macosx-10.6-universal/egg/pika/channel.py|_ensure|84])
</I>&gt;<i>
</I>&gt;<i> Every few seconds Pika will attempt to reconnect the consumer and the
</I>&gt;<i> error repeats. The only unusual error in the Rabbit logs occurs on the
</I>&gt;<i> first reconnection: <A HREF="https://gist.github.com/836441">https://gist.github.com/836441</A>
</I>&gt;<i>
</I>&gt;<i> The rest of the time during these errors the logs look like this:
</I>&gt;<i> <A HREF="https://gist.github.com/836442">https://gist.github.com/836442</A>
</I>&gt;<i>
</I>&gt;<i> The consumer is disconnecting and reconnecting to HAProxy because the
</I>&gt;<i> stats show the connection moving between backend nodes.
</I>&gt;<i>
</I>&gt;<i> The producer continues to operate correctly through the load balancer.
</I>&gt;<i>
</I>&gt;<i> Consumer code is here: <A HREF="https://gist.github.com/836445">https://gist.github.com/836445</A>
</I>&gt;<i>
</I>&gt;<i> Any help/ideas are greatly appreciated. &#160;Thank you in advance.
</I>&gt;<i>
</I>&gt;<i> -J
</I>&gt;<i>
</I></PRE>









































<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="011348.html">[rabbitmq-discuss] Pika reconnection error
</A></li>
	<LI>Next message: <A HREF="011350.html">[rabbitmq-discuss] Pika reconnection error
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#11349">[ date ]</a>
              <a href="thread.html#11349">[ thread ]</a>
              <a href="subject.html#11349">[ subject ]</a>
              <a href="author.html#11349">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">More information about the rabbitmq-discuss
mailing list</a><br>
</body></html>
