<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [rabbitmq-discuss] Error in start_app through rabbitmqctl..
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20Error%20in%20start_app%20through%20rabbitmqctl..&In-Reply-To=%3C1381764572006-30486.post%40n5.nabble.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="030990.html">
   <LINK REL="Next"  HREF="030992.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[rabbitmq-discuss] Error in start_app through rabbitmqctl..</H1>
    <B>k.madnani84</B> 
    <A HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20Error%20in%20start_app%20through%20rabbitmqctl..&In-Reply-To=%3C1381764572006-30486.post%40n5.nabble.com%3E"
       TITLE="[rabbitmq-discuss] Error in start_app through rabbitmqctl..">k.madnani84 at gmail.com
       </A><BR>
    <I>Mon Oct 14 16:29:32 BST 2013</I>
    <P><UL>
        <LI>Previous message: <A HREF="030990.html">[rabbitmq-discuss] AUTO: Lars Ellebo is out of the office.	(returning 21-10-2013)
</A></li>
        <LI>Next message: <A HREF="030992.html">[rabbitmq-discuss] Error in start_app through rabbitmqctl..
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#30991">[ date ]</a>
              <a href="thread.html#30991">[ thread ]</a>
              <a href="subject.html#30991">[ subject ]</a>
              <a href="author.html#30991">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hi,

I am trying to do start_app through rabbitmqctl after doing a stop_app on a
node in a cluster but it throws me error:
Error description:
   {could_not_start,rabbit,
       {bad_return,
           {{rabbit,start,[normal,[]]},
            {'EXIT',
               
{rabbit,failure_during_boot,{badmatch,{error,not_found}}}}}}}

Log files (may contain more information):
   /opt/app/rabbitmq/log/CLUSTER2.log
   /opt/app/rabbitmq/log/CLUSTER2-sasl.log

Error: {rabbit,failure_during_boot,
           {could_not_start,rabbit,
               {bad_return,
                   {{rabbit,start,[normal,[]]},
                    {'EXIT',
                        {rabbit,failure_during_boot,
                            {badmatch,{error,not_found}}}}}}}}

Later i found that if i do a reset and then do start_app it worked.Further
investigating i saw that there was a queue in the node before i was doing
stop_app.Is that the reason why it dint allow me to do start_app and once i
did reset, queue deletes and i could do start_app?



--
View this message in context: <A HREF="http://rabbitmq.1065348.n5.nabble.com/Error-in-start-app-through-rabbitmqctl-tp30486.html">http://rabbitmq.1065348.n5.nabble.com/Error-in-start-app-through-rabbitmqctl-tp30486.html</A>
Sent from the RabbitMQ mailing list archive at Nabble.com.
</PRE>

































































<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="030990.html">[rabbitmq-discuss] AUTO: Lars Ellebo is out of the office.	(returning 21-10-2013)
</A></li>
	<LI>Next message: <A HREF="030992.html">[rabbitmq-discuss] Error in start_app through rabbitmqctl..
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#30991">[ date ]</a>
              <a href="thread.html#30991">[ thread ]</a>
              <a href="subject.html#30991">[ subject ]</a>
              <a href="author.html#30991">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">More information about the rabbitmq-discuss
mailing list</a><br>
</body></html>
