<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [rabbitmq-discuss] AlreadyClosedException always sets hardError	and initiatedByApplication to true
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20AlreadyClosedException%20always%20sets%20hardError%0A%09and%20initiatedByApplication%20to%20true&In-Reply-To=%3C65CCF6A8-199D-4BB4-ABEE-DC79C2413F23%40rabbitmq.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="031198.html">
   <LINK REL="Next"  HREF="031204.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[rabbitmq-discuss] AlreadyClosedException always sets hardError	and initiatedByApplication to true</H1>
    <B>Michael Klishin</B> 
    <A HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20AlreadyClosedException%20always%20sets%20hardError%0A%09and%20initiatedByApplication%20to%20true&In-Reply-To=%3C65CCF6A8-199D-4BB4-ABEE-DC79C2413F23%40rabbitmq.com%3E"
       TITLE="[rabbitmq-discuss] AlreadyClosedException always sets hardError	and initiatedByApplication to true">mklishin at gopivotal.com
       </A><BR>
    <I>Mon Oct 21 21:26:38 BST 2013</I>
    <P><UL>
        <LI>Previous message: <A HREF="031198.html">[rabbitmq-discuss] AlreadyClosedException always sets hardError and initiatedByApplication to true
</A></li>
        <LI>Next message: <A HREF="031204.html">[rabbitmq-discuss] AlreadyClosedException always sets hardError and initiatedByApplication to true
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#31201">[ date ]</a>
              <a href="thread.html#31201">[ thread ]</a>
              <a href="subject.html#31201">[ subject ]</a>
              <a href="author.html#31201">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>On 22 Oct 2013, at 00:17, Jonathan Halterman &lt;<A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">jhalterman at gmail.com</A>&gt; wrote:

&gt;<i> After declaring a consumer on a non-existent queue several times, the connection is still in tact even though the AlreadyClosedException indicates a connection closure
</I>
Consuming from a non-existent queue should result in a channel exception
which closes the channel, not the connection.

MK
</PRE>




































<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="031198.html">[rabbitmq-discuss] AlreadyClosedException always sets hardError and initiatedByApplication to true
</A></li>
	<LI>Next message: <A HREF="031204.html">[rabbitmq-discuss] AlreadyClosedException always sets hardError and initiatedByApplication to true
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#31201">[ date ]</a>
              <a href="thread.html#31201">[ thread ]</a>
              <a href="subject.html#31201">[ subject ]</a>
              <a href="author.html#31201">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">More information about the rabbitmq-discuss
mailing list</a><br>
</body></html>
