<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [rabbitmq-discuss] Pika error - ack/reject throws exception
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20Pika%20error%20-%20ack/reject%20throws%20exception&In-Reply-To=%3CB3F93CAE34C34232BD18ABD35399C42E%40myyearbook.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="018048.html">
   <LINK REL="Next"  HREF="018051.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[rabbitmq-discuss] Pika error - ack/reject throws exception</H1>
    <B>Gavin M. Roy</B> 
    <A HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20Pika%20error%20-%20ack/reject%20throws%20exception&In-Reply-To=%3CB3F93CAE34C34232BD18ABD35399C42E%40myyearbook.com%3E"
       TITLE="[rabbitmq-discuss] Pika error - ack/reject throws exception">gmr at myyearbook.com
       </A><BR>
    <I>Thu Feb  9 17:25:31 GMT 2012</I>
    <P><UL>
        <LI>Previous message: <A HREF="018048.html">[rabbitmq-discuss] Pika error - ack/reject throws exception
</A></li>
        <LI>Next message: <A HREF="018051.html">[rabbitmq-discuss] Installing rabbitmq server in silent mode
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#18049">[ date ]</a>
              <a href="thread.html#18049">[ thread ]</a>
              <a href="subject.html#18049">[ subject ]</a>
              <a href="author.html#18049">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>I have not had time to put in the fix yet, but I am aware of the problem and hope to be able to get to it this weekend.  

Gavin  


On Thursday, February 9, 2012 at 10:13 AM, David Robins wrote:

&gt;<i>  
</I>&gt;<i> I'm using Pika and Python (3.2.2) to access RabbitMQ (2.6.1) queues, on Linux (kernel 3.0.6); specifically, I have some code that creates a blocking connection, binds a channel to a couple of queues, calls
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i> basic_consume on the channel for each queue with no_ack=False, and then start_consuming.
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i>   
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i> It drains a (random - in recent runs I saw 14, 4, then 9) number of messages already in the queue under basic_consume, but then throws the following exception:
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i>   
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i>         Traceback (most recent call last):
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i>                 File &quot;./ep_test&quot;, line 62, in &lt;module&gt;
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i>                         et.track(args.drain)
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i>                 File &quot;./ep_test&quot;, line 41, in track
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i>                         self.q2.consume(callback, auto_ack=False)
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i>                 File &quot;/home/dbrobins/code/utils/tq/broker.py&quot;, line 45, in consume
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i>                         self.brk.chan.basic_consume(thunk, queue=self.qname, no_ack=auto_ack)
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i>                 File &quot;/usr/lib64/python3.2/site-packages/pika-0.9.5-py3.2.egg/pika/channel.py&quot;, line 368, in basic_consume
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i>                         [spec.Basic.ConsumeOk])
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i>                 File &quot;/usr/lib64/python3.2/site-packages/pika-0.9.5-py3.2.egg/pika/adapters/blocking_connection.py&quot;, line 224, in rpc
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i>                         frame = self._frames[reply]
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i>         KeyError: 'Basic.ConsumeOk'
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i>   
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i> Am I doing something wrong in thinking I can ack a message in this state? It doesn't throw an exception with no_ack=True. If so, what? Or is it a bug in the pika module or a problem with RabbitMQ?
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i>   
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i> I've done a little debugging and it's possible I'm getting two Basic.ConsumeOk frames - if so, would that be a bug in RabbitMQ or does the client need to expect this? Is there a way to get verbose debug
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i> output from RabbitMQ? - searches indicate no, except perhaps to watch it with an independent network tracing tool? Thanks for any help.
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i>   
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i> &#8230;
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i>   
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i> This is likely an instance of issue #70 on GitHub (<A HREF="https://github.com/pika/pika/issues/70">https://github.com/pika/pika/issues/70</A>) which says &#8220;Pending Fix&#8221; &#8211; does that mean that a fix is available but unreleased, or that there is no fix yet?
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i>  
</I>&gt;<i> _______________________________________________
</I>&gt;<i> rabbitmq-discuss mailing list
</I>&gt;<i> <A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">rabbitmq-discuss at lists.rabbitmq.com</A> (mailto:<A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">rabbitmq-discuss at lists.rabbitmq.com</A>)
</I>&gt;<i> <A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss</A>
</I>&gt;<i>  
</I>&gt;<i>  
</I>

-------------- next part --------------
An HTML attachment was scrubbed...
URL: &lt;<A HREF="http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/attachments/20120209/088ff6ba/attachment.htm">http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/attachments/20120209/088ff6ba/attachment.htm</A>&gt;
</PRE>




























































<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="018048.html">[rabbitmq-discuss] Pika error - ack/reject throws exception
</A></li>
	<LI>Next message: <A HREF="018051.html">[rabbitmq-discuss] Installing rabbitmq server in silent mode
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#18049">[ date ]</a>
              <a href="thread.html#18049">[ thread ]</a>
              <a href="subject.html#18049">[ subject ]</a>
              <a href="author.html#18049">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">More information about the rabbitmq-discuss
mailing list</a><br>
</body></html>
