<tt>
Hello,&lt;br&gt;&lt;br&gt;We&nbsp;are&nbsp;using&nbsp;rabbit&nbsp;cluster&nbsp;for&nbsp;a&nbsp;few&nbsp;months&nbsp;now&nbsp;and&nbsp;things&nbsp;have&nbsp;been&nbsp;working&nbsp;fine&nbsp;until&nbsp;now.&lt;br&gt;&lt;br&gt;ENVIORNMENT&lt;br&gt;=============&lt;br&gt;RabbitMQ&nbsp;Server&nbsp;version&nbsp;2.8.2&lt;br&gt;RabbitMQ&nbsp;Client&nbsp;2.7.1&lt;br&gt;&lt;br&gt;One&nbsp;of&nbsp;our&nbsp;applications&nbsp;is&nbsp;consuming&nbsp;messages&nbsp;from&nbsp;RabbitMQ&nbsp;server&nbsp;over&nbsp;WAN.&lt;br&gt;<br>
This&nbsp;was&nbsp;a&nbsp;recent&nbsp;introduction&nbsp;i.e.&nbsp;going&nbsp;over&nbsp;WAN&nbsp;to&nbsp;a&nbsp;diff.&nbsp;RabbitMQ&nbsp;cluster&nbsp;than&nbsp;the&nbsp;local&nbsp;one.&lt;br&gt;After&nbsp;a&nbsp;few&nbsp;hours&nbsp;of&nbsp;being&nbsp;up&nbsp;and&nbsp;consuming&nbsp;messages,&nbsp;one&nbsp;of&nbsp;the&nbsp;many&nbsp;channels&nbsp;in&nbsp;the&nbsp;application&nbsp;&lt;br&gt;is&nbsp;closed&nbsp;by&nbsp;the&nbsp;server&nbsp;with&nbsp;the&nbsp;following&nbsp;message.&lt;br&gt;<br>
&lt;br&gt;{#method&amp;lt;channel.close&amp;gt;(reply-code=406,&nbsp;reply-text=PRECONDITION_FAILED&nbsp;-&nbsp;unknown&nbsp;delivery&nbsp;tag&nbsp;1073743883,&nbsp;class-id=60,&nbsp;method-id=80),&nbsp;null,&nbsp;&amp;quot;[B@607daec3&amp;quot;}&lt;br&gt;&lt;br&gt;From&nbsp;what&nbsp;i&nbsp;have&nbsp;read&nbsp;so&nbsp;far&nbsp;it&nbsp;seems&nbsp;like&nbsp;a&nbsp;problem&nbsp;of&nbsp;double&nbsp;ack.&nbsp;but&nbsp;it&nbsp;could&nbsp;be&nbsp;something&nbsp;totally&nbsp;different.&lt;br&gt;<br>
Application&nbsp;creates&nbsp;multiple&nbsp;Connection/Channel&nbsp;pairs&nbsp;and&nbsp;each&nbsp;is&nbsp;assigned&nbsp;its&nbsp;own&nbsp;Consumer&nbsp;instance.&lt;br&gt;We&nbsp;have&nbsp;a&nbsp;single&nbsp;consumer&nbsp;per&nbsp;channel&nbsp;per&nbsp;connection.&lt;br&gt;&lt;br&gt;Here&amp;#39;s&nbsp;a&nbsp;snippet&nbsp;of&nbsp;code&nbsp;from&nbsp;Consumer.handleDelivery()&nbsp;method&nbsp;modified&nbsp;to&nbsp;remove&nbsp;business&nbsp;specific&nbsp;information.&lt;br&gt;<br>
But&nbsp;this&nbsp;is&nbsp;the&nbsp;gist&nbsp;of&nbsp;what&nbsp;happens&nbsp;when&nbsp;a&nbsp;message&nbsp;is&nbsp;received.&lt;br&gt;&lt;br&gt;   &nbsp;public&nbsp;final&nbsp;void&nbsp;handleDelivery(String&nbsp;consumerTag,&nbsp;Envelope&nbsp;envelope,&lt;br&gt;           &nbsp;BasicProperties&nbsp;properties,&nbsp;byte[]&nbsp;body)&nbsp;throws&nbsp;IOException&nbsp;{&lt;br&gt;<br>
&lt;br&gt;       &nbsp;boolean&nbsp;failed&nbsp;=&nbsp;false;&lt;br&gt;       &nbsp;Throwable&nbsp;failureReason&nbsp;=&nbsp;null;&lt;br&gt;       &nbsp;try&nbsp;{&lt;br&gt;           &nbsp;//&nbsp;create&nbsp;a&nbsp;delivery&nbsp;for&nbsp;the&nbsp;client&lt;br&gt;           &nbsp;delivery&nbsp;=&nbsp;createDelivery(consumerTag,&nbsp;body,&nbsp;envelope,&nbsp;properties);&lt;br&gt;<br>
           &nbsp;//&nbsp;deliver&nbsp;to&nbsp;client&lt;br&gt;           &nbsp;deliveryHandler.handleDelivery(delivery);&lt;br&gt;       &nbsp;}&nbsp;catch&nbsp;(Throwable&nbsp;e)&nbsp;{&lt;br&gt;           &nbsp;//&nbsp;client&nbsp;had&nbsp;a&nbsp;problem&nbsp;handling/processing&nbsp;delivery&lt;br&gt;           &nbsp;failed&nbsp;=&nbsp;true;&lt;br&gt;<br>
           &nbsp;failureReason&nbsp;=&nbsp;e;&lt;br&gt;           &nbsp;log.error(&amp;quot;Client&nbsp;failed&nbsp;while&nbsp;handling&nbsp;delivery.&nbsp;&amp;quot;&lt;br&gt;                   &nbsp;+&nbsp;e.getMessage(),&nbsp;e);&lt;br&gt;       &nbsp;}&nbsp;finally&nbsp;{&lt;br&gt;           &nbsp;if&nbsp;(failed)&nbsp;{&lt;br&gt;               &nbsp;handleFailedDelivery(&lt;br&gt;<br>
                       &nbsp;failureReason,&nbsp;body,&nbsp;properties);&lt;br&gt;           &nbsp;}&nbsp;else&nbsp;{&lt;br&gt;               &nbsp;try&nbsp;{&lt;br&gt;                   &nbsp;acknowledge(envelope.getDeliveryTag());&lt;br&gt;               &nbsp;}&nbsp;catch&nbsp;(Exception&nbsp;e)&nbsp;{&lt;br&gt;                   &nbsp;notifyClient(e);&lt;br&gt;<br>
               &nbsp;}&lt;br&gt;           &nbsp;}&lt;br&gt;       &nbsp;}&lt;br&gt;   &nbsp;}&lt;br&gt;<br>
&lt;br&gt;Envelope&nbsp;object&nbsp;that&nbsp;is&nbsp;handed&nbsp;to&nbsp;the&nbsp;method&nbsp;as&nbsp;an&nbsp;argument&nbsp;stays&nbsp;method&nbsp;local.&lt;br&gt;Our&nbsp;application&nbsp;is&nbsp;connecting&nbsp;to&nbsp;the&nbsp;cluster&nbsp;through&nbsp;a&nbsp;netscaler&nbsp;VIP.&lt;br&gt;&lt;br&gt;We&nbsp;have&nbsp;not&nbsp;seen&nbsp;this&nbsp;problem&nbsp;when&nbsp;consuming&nbsp;from&nbsp;a&nbsp;local&nbsp;cluster&nbsp;with&nbsp;the&nbsp;same&nbsp;application.&lt;br&gt;<br>
&lt;br&gt;Any&nbsp;help&nbsp;or&nbsp;pointer&nbsp;in&nbsp;the&nbsp;right&nbsp;direction&nbsp;is&nbsp;appreciated.&lt;br&gt;&lt;br&gt;Thanks,&lt;br&gt;Vineet&lt;br&gt; &lt;br&gt;
</tt>
