<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [rabbitmq-discuss] socket error while using rabbitmq and a NAT (Network address translation)
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20socket%20error%20while%20using%20rabbitmq%20and%20a%20NAT%0A%20%28Network%20address%20translation%29&In-Reply-To=%3CAANLkTim3tiKG4K%2Bp23ms-qO00r66ojPk4A1m_%3D050mMK%40mail.gmail.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="011570.html">
   <LINK REL="Next"  HREF="011576.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[rabbitmq-discuss] socket error while using rabbitmq and a NAT (Network address translation)</H1>
    <B>mysurf mail</B> 
    <A HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20socket%20error%20while%20using%20rabbitmq%20and%20a%20NAT%0A%20%28Network%20address%20translation%29&In-Reply-To=%3CAANLkTim3tiKG4K%2Bp23ms-qO00r66ojPk4A1m_%3D050mMK%40mail.gmail.com%3E"
       TITLE="[rabbitmq-discuss] socket error while using rabbitmq and a NAT (Network address translation)">stammailbox at gmail.com
       </A><BR>
    <I>Wed Mar  2 07:41:20 GMT 2011</I>
    <P><UL>
        <LI>Previous message: <A HREF="011570.html">[rabbitmq-discuss] socket error while using rabbitmq and a NAT (Network address translation)
</A></li>
        <LI>Next message: <A HREF="011576.html">[rabbitmq-discuss] socket error while using rabbitmq and a NAT (Network address translation)
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#11571">[ date ]</a>
              <a href="thread.html#11571">[ thread ]</a>
              <a href="subject.html#11571">[ subject ]</a>
              <a href="author.html#11571">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Flash News :
I am sorry to bother you a lot this morning . But I have an interesting
finding
When I activate my client with the tracer - it connects well to the rabbitmq
server .
when I connect directly - it throws that exception .

So maybe my problem is with the connection string ?
here it is - I only replace the  ip and port
BasicChannel(Username, Password, VirtualHost, BrokerIp, BrokerPort,
Heartbeat);
BasicChannel(Username, Password, VirtualHost, &quot;127.0.0.1&quot;,5672, Heartbeat);

and my ctor is

public BasicChannel(final String username, final String password,
final String virtualHost, final String brokerIp, final int brokerPort,
int heartbeat) {
        ConnectionFactory factory = new ConnectionFactory();
        factory.setUsername(username);
        factory.setPassword(password);
        factory.setVirtualHost(virtualHost);
        factory.setRequestedHeartbeat(heartbeat);
        factory.setHost(brokerIp);
        factory.setPort(brokerPort);

        connection = null;
        try {
            connection = factory.newConnection();
        } catch (IOException e) {
            throw new PlatformException(&quot;could not create connection&quot;, e);
        }



Thanks


On Wed, Mar 2, 2011 at 9:26 AM, mysurf mail &lt;<A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">stammailbox at gmail.com</A>&gt; wrote:

&gt;<i> Sorry,
</I>&gt;<i> I get PossibleAuthenticationFailureException
</I>&gt;<i>
</I>&gt;<i> PlatformException: could not create connection
</I>&gt;<i> 	at com.programa17.mmm.modules.stopwatch.util.BasicChannel.&lt;init&gt;(BasicChannel.java:40)
</I>&gt;<i> 	at com.programa17.mmm.modules.stopwatch.util.BasicChannel.&lt;init&gt;(BasicChannel.java:23)
</I>&gt;<i> 	at com.programa17.mmm.modules.stopwatch.util.RabbitMQTest$Manager.&lt;init&gt;(RabbitMQTest.java:94)
</I>&gt;<i> 	at com.programa17.mmm.modules.stopwatch.util.RabbitMQTest.test1(RabbitMQTest.java:22)
</I>&gt;<i> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
</I>&gt;<i> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
</I>&gt;<i> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
</I>&gt;<i> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
</I>&gt;<i> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
</I>&gt;<i> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
</I>&gt;<i> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
</I>&gt;<i> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
</I>&gt;<i> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
</I>&gt;<i> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
</I>&gt;<i> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
</I>&gt;<i> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
</I>&gt;<i> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
</I>&gt;<i> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
</I>&gt;<i> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
</I>&gt;<i> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
</I>&gt;<i> 	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:65)
</I>&gt;<i> Caused by: com.rabbitmq.client.PossibleAuthenticationFailureException: Possibly caused by authentication failure
</I>&gt;<i> 	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:289)
</I>&gt;<i> 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:383)
</I>&gt;<i> 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:403)
</I>&gt;<i> 	at com.programa17.mmm.modules.stopwatch.util.BasicChannel.&lt;init&gt;(BasicChannel.java:38)
</I>&gt;<i> 	... 23 more
</I>&gt;<i> Caused by: com.rabbitmq.client.AlreadyClosedException: clean connection shutdown; reason: Attempt to use closed channel
</I>&gt;<i> 	at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:181)
</I>&gt;<i> 	at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:208)
</I>&gt;<i> 	at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:194)
</I>&gt;<i> 	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:281)
</I>&gt;<i> 	... 26 more
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> On Wed, Mar 2, 2011 at 9:01 AM, mysurf mail &lt;<A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">stammailbox at gmail.com</A>&gt; wrote:
</I>&gt;<i>
</I>&gt;&gt;<i> Ok,
</I>&gt;&gt;<i> I will repeat my test results fully .
</I>&gt;&gt;<i> It happens only from certain computers.
</I>&gt;&gt;<i> It usually throws an exception when the command
</I>&gt;&gt;<i> factory.newConnection() is invoked.
</I>&gt;&gt;<i> the exception is ConnectionException. I have it in the initial mail of
</I>&gt;&gt;<i> this thread.
</I>&gt;&gt;<i> ( I can telnet that port. I can connect from other computers. I can
</I>&gt;&gt;<i> connect to it with 1.7.0 clients )
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> I dont think I am acking until that point.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> On Tue, Mar 1, 2011 at 5:59 PM, Emile Joubert &lt;<A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">emile at rabbitmq.com</A>&gt; wrote:
</I>&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> Hi,
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> On 01/03/11 14:57, mysurf mail wrote:
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> Hi,
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> I setup a trace at the client app server. Set the listen port and
</I>&gt;&gt;&gt;&gt;<i> connection port and got a log for the unsuccessful
</I>&gt;&gt;&gt;&gt;<i> factory.newConnection() . I added it in attached the tracelog.txt.
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> This looks like a normal trace with a successful connection
</I>&gt;&gt;&gt;<i> establishment, and subsequent exchange and queue declarations. I would be
</I>&gt;&gt;&gt;<i> surprised if the broker logfile contained an abrupt connection failure at
</I>&gt;&gt;&gt;<i> the corresponding time. Can you please confirm? If possible please supply a
</I>&gt;&gt;&gt;<i> trace of a case where an error occurs.
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>  now regarding the other references you gave me
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> 1 Protocol errors:
</I>&gt;&gt;&gt;&gt;<i>  Acknowledging with an unknown delivery tag
</I>&gt;&gt;&gt;&gt;<i>  Redeclaring exchanges with different parameters
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> you recommended not acking more than once. This whole thing started when
</I>&gt;&gt;&gt;&gt;<i> we upgraded the rabbitmq version and Matthias sujested we will change
</I>&gt;&gt;&gt;&gt;<i> the consumer to ack (i.e. we changed it to
</I>&gt;&gt;&gt;&gt;<i> channel.basicConsume(queueName, FALSE, queueingConsumer);)
</I>&gt;&gt;&gt;&gt;<i> (This is if I understood him right )
</I>&gt;&gt;&gt;&gt;<i> So How can I control the acking . How do I know if I ack more then once.
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> This is more than a recommendation. From the specification:
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>  &quot;a client MUST not acknowledge the same message more than once.&quot;
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> Check whether your client contains instances of &quot;channel.basicAck&quot;. If
</I>&gt;&gt;&gt;<i> you acknowledge messages more than once you will see a channel exception.
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> Emile
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;<i>
</I>-------------- next part --------------
An HTML attachment was scrubbed...
URL: &lt;<A HREF="http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/attachments/20110302/c6d31058/attachment.htm">http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/attachments/20110302/c6d31058/attachment.htm</A>&gt;
</PRE>





<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="011570.html">[rabbitmq-discuss] socket error while using rabbitmq and a NAT (Network address translation)
</A></li>
	<LI>Next message: <A HREF="011576.html">[rabbitmq-discuss] socket error while using rabbitmq and a NAT (Network address translation)
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#11571">[ date ]</a>
              <a href="thread.html#11571">[ thread ]</a>
              <a href="subject.html#11571">[ subject ]</a>
              <a href="author.html#11571">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">More information about the rabbitmq-discuss
mailing list</a><br>
</body></html>
