<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [rabbitmq-discuss] Rabbitmq With Celery Problem, Error 541
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20Rabbitmq%20With%20Celery%20Problem%2C%20Error%20541&In-Reply-To=%3CCADuqQqbGhvwbXxu9rgmkn%2Bi-n7TRwGB3wH0zTDUbJNK3J1aXew%40mail.gmail.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="016370.html">
   <LINK REL="Next"  HREF="016470.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[rabbitmq-discuss] Rabbitmq With Celery Problem, Error 541</H1>
    <B>Mike Grouchy</B> 
    <A HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20Rabbitmq%20With%20Celery%20Problem%2C%20Error%20541&In-Reply-To=%3CCADuqQqbGhvwbXxu9rgmkn%2Bi-n7TRwGB3wH0zTDUbJNK3J1aXew%40mail.gmail.com%3E"
       TITLE="[rabbitmq-discuss] Rabbitmq With Celery Problem, Error 541">mgrouchy at gmail.com
       </A><BR>
    <I>Fri Nov 18 18:53:25 GMT 2011</I>
    <P><UL>
        <LI>Previous message: <A HREF="016370.html">[rabbitmq-discuss] Rabbitmq With Celery Problem, Error 541
</A></li>
        <LI>Next message: <A HREF="016470.html">[rabbitmq-discuss] Rabbitmq With Celery Problem, Error 541
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#16372">[ date ]</a>
              <a href="thread.html#16372">[ thread ]</a>
              <a href="subject.html#16372">[ subject ]</a>
              <a href="author.html#16372">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>On Fri, Nov 18, 2011 at 1:26 PM, Ask Solem &lt;<A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">ask at celeryproject.org</A>&gt; wrote:
&gt;<i> Maybe you should try enabling the pool. &#160;Either way it should retry publishing the result, so maybe this is yet another corner case in amqplib. &#160;It would be great if you could try to create a small test case that is able to reproduce the issue.
</I>&gt;<i>
</I>&gt;<i> --
</I>&gt;<i> Ask Solem
</I>&gt;<i>
</I>

Okay,

So I enabled the pool set it to 12 (Seemed like a reasonable number
for the BROKER_POOL_LIMIT). So I ran the task the first time and it
seemed like it ran okay. I just got back from lunch and tried to run
it again to see if maybe enabling the pool fixed the problem, but now
we seem to have some more datapoints here.

I have attached the celery log output (from --INFO ) and the rabbitmq.log

<A HREF="https://gist.github.com/81e6f762410e6e4813aa">https://gist.github.com/81e6f762410e6e4813aa</A>

So it seems like we are running into a too many processes error, but I
thought the upper bound was around 30K, which I can't imagine I would
be using (even though, there are around 60k tasks).

I can't seem to replicate it consistently, which is making it hard to
narrow down to a specific test case.

Any insight here?

Thanks,
Mike





&gt;<i> On Nov 18, 2011, at 1:15 PM, Mike Grouchy &lt;<A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">mgrouchy at gmail.com</A>&gt; wrote:
</I>&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> On 2011-11-18, at 8:09 AM, Ask Solem &lt;<A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">ask at rabbitmq.com</A>&gt; wrote:
</I>&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> On 18 Nov 2011, at 01:27, Mike Grouchy wrote:
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> Hi There,
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> I'm having this issue where I have a script that runs on a cronjob
</I>&gt;&gt;&gt;&gt;<i> that runs a rather large amount of tasks against celery(around 60K or
</I>&gt;&gt;&gt;&gt;<i> so tasks). It seems like after I get through a large portion of the
</I>&gt;&gt;&gt;&gt;<i> tasks I start getting error 541's returned from the celery workers
</I>&gt;&gt;&gt;&gt;<i> which seems to be bubbling up from rabbitmq.
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> Here is the relevant portion of the log <A HREF="https://gist.github.com/c92d42929e514cbb69fa">https://gist.github.com/c92d42929e514cbb69fa</A>
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> The weird thing is I am not seeing any error in the rabbitmq logs, but
</I>&gt;&gt;&gt;&gt;<i> as far as I know the error is coming from rabbitmq.
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i> Can anyone point me in the direction on what I can do to prevent this
</I>&gt;&gt;&gt;&gt;<i> from continuing to happen?
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> Seems to me like you have lost the connection to RabbitMQ while trying
</I>&gt;&gt;&gt;<i> to publish task results.
</I>&gt;&gt;&gt;<i>
</I>&gt;&gt;&gt;<i> Are you using BROKER_POOL_LIMIT?
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> No. Currently just the defaults.
</I>&gt;<i>
</I>&gt;<i>
</I></PRE>






































































<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="016370.html">[rabbitmq-discuss] Rabbitmq With Celery Problem, Error 541
</A></li>
	<LI>Next message: <A HREF="016470.html">[rabbitmq-discuss] Rabbitmq With Celery Problem, Error 541
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#16372">[ date ]</a>
              <a href="thread.html#16372">[ thread ]</a>
              <a href="subject.html#16372">[ subject ]</a>
              <a href="author.html#16372">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">More information about the rabbitmq-discuss
mailing list</a><br>
</body></html>
